server:
  port: 8080

spring:
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_empty
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/jsc_web?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://192.8.141.199:3306/jsc_web?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&allowPublicKeyRetrieval=true
    username: root
#    password: root
    password: 1999114zzm

  jpa:
    properties:
      hibernate.jdbc.time_zone: Asia/Shanghai
    hibernate:
      ddl-auto: update
    show-sql: false

jsc:
  config:
    linux-ip: 192.8.141.199
    python-url: D:/Anaconda/envs/python3.5/python
    save-path: D:/
    upgrade-path: /u01/install
    config-default: D:/IDEA/jsc-parent/jsc-api/src/main/resources/config_default.py
    export-procedure: D:/IDEA/jsc-parent/jsc-api/src/main/resources/config_export.py
    import-procedure: D:/IDEA/jsc-parent/jsc-api/src/main/resources/config_import.py