server:
  port: 8080
#  address: 127.0.0.1

# (//*([^*]|[/r/n]|(/*+([^*/]|[/r/n])))*/*+/|[ /t]*//.*)
#

#  ssl:
#    enabled: true
#    # SSL/TLS: Support Weak SSLv3/TLS1.0/TLS1.1 Protocol
#    enabled-protocols: [ TLSv1.2 ]
#    # Diffie-Hellman Key Exchange Insufficient DH Group Strength Vulnerability
#    ciphers: [ TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA,SSL_RSA_WITH_RC4_128_SHA ]
#    key-store: classpath:www.b-du.com.jks
#    key-store-password: JSC@3passok
#    key-store-type: JKS

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/jsc_web?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    #    url: jdbc:mysql://192.168.17.54:3306/jsc_web?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  # password: 1999114zzm

  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: update
    show-sql: true

jsc:
  config:
    #    linux-ip: 192.8.141.199
    linux-ip: 127.0.0.1
    #    python-url: D:/Anaconda/envs/python3.5/python
    python-url: python
    #    save-path: D:/
    save-path: /u01/pos
    #    config-default: D:/IDEA/jsc-parent/jsc-api/src/main/resources/config_default.py
    config-default: /home/web/config_default.py
    #    export-procedure: D:/IDEA/jsc-parent/jsc-api/src/main/resources/config_export.py
    export-procedure: /home/web/config_export.py
    #    import-procedure: D:/IDEA/jsc-parent/jsc-api/src/main/resources/config_import.py
    import-procedure: /home/web/config_import.py